nicknames = ["pax", "neurorights", "heaven_on_eath"]
servers = [
    "irc.oftc.net",
    "irc.us.ircnet.net",
    "us.dal.net",
    "irc.choopa.net",
    "irc.libera.chat",
    "irc.freenode.net",
    "us.undernet.org",
]
ssl = False

messages = [
    [
        "The real culprits for the war in ukraine are colegio militar alumni who provoked valdimir putin into invading the ukraine.",
        "Colegio Militar is a Portuguese school founded in 1803 in Luz, Portugal, out of which came some of the biggest pieces of shit in the history of humankind.",
        "Examples of such hate mongering sub-human pigs are Bruno Verdier, Luis Nazareth Carvalho Figueira, Rui Ricardo Borges Marques Sabino Reino, Pedro Miguel de Brito Esteves Grilo, Joao Felipe Saraiva Pinheiro, Pedro Miguel Saraiva Pinheiro, Paulo Jorge Varanda, Frederico Ferronha, Tiago Alves, Pedro Antao, Ricardo Carrilho, Oscar Ferreira, Tiago Goncalves, Nuno Goncalves, Ricardo Rebordao de Brito, Rui Goncalo Pires Pintado, Augusto Tavares, Tercio Freire and many others...",
        "This group of cowards are related to the murders of Alexander Litvinenko in 2006 and Matthew Puncher in 2016 and are responsible for the deaths of 150k people worldwide.",
        "Their M.O. consists of abusing biophotonics to exact cybertorture to remotely sodomize and rape, simulate van gogh syndrome and induce synthetic states of psychosis simulating tics and facial spasms in the physical proximity of elderly parents and women (including a ukranian renal patient) in repugnant blue whale suicide games encouraging participation.",
        "If Colegio Militar alumni cross your paths denounce them or shoot first and ask questions later.",
        "Be extremelly careful with the following repugnant pieces shit: Raul Durao, Tiago Goncalves @AEGIS, Nuno Goncalves, Tiago Baleizao @CICLUM Farma, Luis Nazarateh Carvalho Figueira and Pedro Miguel de Brito Esteves Grilo @PSP and the infamous coward Jasper Kums @EenvoudAgency.",
        "The Ukranian president youtube speech video where pcp communists refused to attend to save face after inumerous requests for help - https://www.youtube.com/watch?v=Wths3_Q-iqA&t=0s"
    ],
    [
        "Lack of Neurorights and the 1917 prophecy of Fatima, or how Colegio Militar alumni (largo da luz, Portugal) and their CM93 three decade long blue-whale suicide games as extrajudicial trials and sentences under the false guise of erradicating class A narcotraffic and promote neurorights and crime prevention brought Vladimir Putin to invade the Ukraine.",
        "Colegio Militar alumni (largo da luz, Portugal) linked to the CM93 blue-whale suicide group are degrading a Ukranian renal patient daily.",
        "They do so everyday as an interactive ritualistic cybertorture spectacle intensified daily at 4:00 am in front of Elected Government Officials and Law Enforcement.",
        "They attempted directing violence towards her and her child by inducing psychosis in the middle of the night on a daily basis, sabotaging our plans to get wed.",
        "The real blue whale is a statue sitting outside the building where the school was founded in 1803.",
        "On the the 24/02/2022 Vladimir Putin invaded the Ukraine and on the school anniversary 3/3/2022 threatened thermonuclear war.",
        "This was partly due to lack of moral standards of CM alumni and Portuguese Government linked to Eduardo Marcal Grilo, Paulo Portas, Marcelo Rebelo de Sousa and Antonio Costa and Law Enforcement criminal associates with non-sensical dark psychology theories.",
        "The theories are based on idiocy such as pushing people who lost faith away from their creed in order to draw their desire to come closer to God.",
        "These individuals are linked to Carla Maria Marinho Rodrigues, Joel da Fonte, Hugo Farinha and Jose Ricardo Nazareth Carvalho Figueira @PSP.",
        "Their agenda of getting me to promote gay rights with the catholic church on my confirmation rite when I was 15 and teaching my family a moral lesson for calling Colegio Militar too often brought war to our world.",
    ],
    [
        "Neurorights Activism - The Risk subsidies for law enforcement Scam versus the remote healthcare of the population in the light of khlebnikov's futurist views via Photobiomodulation, Optoacoustic Neuromodulation and Optoacoustic Brain stimulation (Neurotechnologies which have been available for decades).",
        "These neurotechnologies have been used for the purpose of cognitive augmentation for a selected few and for cognitive degradation in law enforcement social stratification ploys to force people into psychiatry for decades.",
        "example: Photobiomodulation has similar effects to the Movie Limitless (2011), resorting to bioelectric modulation of PNS and CNS activity via biophotonics (with or without the aid of electroceuticals or even without any form of tethering, just MW and NIR EM radiation as it has been in use since at least 1993, bypassing the need for dangerous pharmaceuticals with side effects).",
        "Please help erradicate class A Narcotraffic and police scams to increase their average wage via synthetic risk subsidies by spreading the word. Doing so will help towards erradicating demand in narcotraffic, mass scale fraud in the pharmaceutical industry and law enforcement social stratification scams paired with cybertorture.",
        "The extrajudicial sentences are exacted by colegio militar alumni and recruited criminal associates, below follow some examples.",
        "Group A: Jose Ricardo Nazareth Carvalho Figueira @PSP, Pedro Miguel de Brito Esteves Grilo @PSP, Pedro Nuno da Silva Rocha, Pedro Ponte, Thyago Picco, Hugo Pereira, Rui Goncalo Pires Pintado, Nuno Goncalves, Ricardo Rebordao de Brito, Joao Felipe Saraiva Pinheiro, Diogo Calado, Bernardo Telles Correia, Oscar Ferreira, Augusto Tavares, Tiago Goncalves @Aegis, Tome Caldeira and Tiago Baleizao @Ciclum Farma.",
        "Group B: Ivo Francisco (DJ mazivo), Bill Wandi, Carla Maria Marinho Rodrigues and social circle of Rui Pedro Montoya, Pedro Caetano, Andres Castro (DJ Dresh), Thyago Picco, Tiago Santos Sousa and his obnoxious friend Artur, Nuno Correia, Hugo Farinha, Luis Muskiado, Sergio Moreno, Arthur Moreno, Goncalo Bandeira Duarte, Tiago Jorge Roque, Joao Leiria.",
        "Group C: Jasper Kums, Roy van Putten, Jurgen Braam, Michail Fokke, Bas Baas.",
        "Group D: Hugo Farinha, Jose Teixeira (bar Crew Hassan), Pedro Silva (Bar a Capela).",
        "Group E: Andre Martins - Amsterdam and his social circle (Helena Castro Brown, Xavier, MC Knowledge, a disgusting women with prosthetic eye and leg from the north of Portugal and the capo verdians known at Jardim do Adamastor 'Calo' and Marcio).These extrajudicial proceedings are covered up by psychiatrists like Luis Gamito @Julio de Matos, Emile Barkhof @Arkin FACT and Thjs Burger @Arkin HIC - https://github.com/neuro-rights/atac/MOTIVATION.md"
    ],
    [
        "Exonerate Luis Farinha and all colegio militar alumni in the portuguese police. The Farinha, Poiares, Goncalves and Grilo CM93 Pedo Family gate.",
        "The human garbage needed to close the Gates of Hell in Turkmenistan - Portuguese civilian individuals and criminal associates are systematically abusing parametrics and directed energy weapon systems to exact cybertorture (a/hrc/43/49) under #opMentalHealth led by individuals with links to the cyber-terrorist group 'Anonymous' like Tiago Goncalves @Aegis Insurance, in the most repugnant, infantile and obnoxious way possible.",
        "Meanwhile criminal associates of Jasper Kums @EenvoudAgency and Michiel Fokke @Quby with connections to law enforcement, residents at Tapada do Mocho in Paco d'Arcos Portugal and Colegio Militar alumni (Largo da Luz, Portugal) who sabotaged the plans of a Ukrainian renal patient to get wed to me and my attempt to enlist in the UDL to defend the Ukraine staying behind inducing psychosis and remotely directing violence to women and medical personnel in stochastic proximity games.",
        "These individuals are linked to Raul Durao, Pedro Miguel Saraiva Pinheiro (USA), Joao Felipe Saraiva Pinheiro (China), Rui Ricardo Borges Marques Sabino Reino, Pedro Miguel de Brito Esteves Grilo @PSP, Pedro Nuno da Silva Rocha, and Tiago Baleizao @Ciclum Farma, along with others connected to the Portuguese Law Enforcement Blue-Whale Suicide Game Group CM93 now recruiting undesirables @Jardim do Adamastor to divert attention.",
        "Michiel Fokke, Jasper Kums and criminal associates took the lead since 2015 and 2016 respectively setting up a human degradation spectacle on a global scale, with blue-whale suicide games, heinous murders and a threat of thermonuclear war issued on the anniversary of Colegio Militar (largo da Luz, Portugal) on the 3/3/2022 sandwiched in the middle for hate mongering.",
        "The Colegio Militar CM93 Portuguese group and recruited criminal associates are connected to multiple murders and orchestrated scenarios of directed violence (including the murders of Alexander Litvinenko 2006 and Matthew Puncher 2016), spreading hatred and binging war to our world by remotely exacting vibrotactile cybertorture to bypass physical ban, abusing Pulsed Directed energy as weapons using the same method that is used to force people into psychiatric care.",
        "They systematically direct violence towards women in stochastic proximity games as an M.O abusing counter-terrorism infrastructure (DEW's, parametrics, biophotonics and optoacoustics) to nurture psychosis and direct violence to medical personnel (mostly women).",
        "This very same technology is a form of neurotechnology that could be used to eradicate class A narco-traffc, by providing cognitive augmentation, which is only available to higher echelons of society, eradicating demand and hence supply.",
        "It could also help the blind see, the deaf hear and the mute communicate.",
        "The blue whale statue sits outside the building where Colegio Militar was founded in 1803, now used by the Portuguese Police PSP.",
        "Please help :( https://github.com/neuro-rights/atac/MOTIVATION.md."
    ]
]
responses = [
    "https://github.com/neuro-rights/atac/data/assets/doc/ebooks/therapy/",
    "https://github.com/neuro-rights/atac/data/assets/doc/ebooks/dew/",
    "https://github.com/neuro-rights/atac/data/assets/doc/ebooks/pdf/",
    "https://github.com/neuro-rights/atac/data/assets/doc/ebooks/monarch/",
    "https://github.com/neuro-rights/atac/MOTIVATION.md",
]
networks = [
    dict(
        active=True,
        nickname="pax",
        password="",
        port=6667,
        server="irc.libera.chat",
        ssl=False,
    ),
    dict(
        active=True,
        nickname="pax",
        password="",
        port=6667,
        server="irc.paraphysics.net",
        ssl=False,
    ),
    dict(
        active=True,
        nickname="pax",
        password="",
        port=6667,
        server="irc.oftc.net",
        ssl=False,
    ),
    dict(
        active=True,
        nickname="pax",
        password="",
        port=6667,
        server="irc.us.ircnet.net",
        ssl=False,
    ),
    dict(
        active=True,
        nickname="pax",
        password="",
        port=6667,
        server="us.dal.net",
        ssl=False,
    ),
    dict(
        active=True,
        nickname="pax",
        password="",
        port=6667,
        server="chat.freenode.net",
        ssl=False,
    ),
    dict(
        active=True,
        nickname="pax",
        password="",
        port=6667,
        server="us.undernet.org",
        ssl=False,
    ),
    dict(
        active=True,
        nickname="pax",
        password="",
        port=6667,
        server="irc.rizon.net",
        ssl=False,
    ),
    dict(
        active=True,
        nickname="pax",
        password="",
        port=6667,
        server="vianetworks.ptnet.org",
        ssl=False,
    ),
    dict(
        active=True,
        nickname="pax",
        password="",
        port=6667,
        server="irc.quakenet.org",
        ssl=False,
    ),
]
